### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by sscotth** [nss-day-cohort-15/static-web-js-quiz-ewilliamswtn#1]
First, make sure to use pull requests and a quiz branch in the future. It allows for making contextual comments much easier.

**Comment by sscotth** [comment]
https://github.com/nss-day-cohort-15/static-web-js-quiz-ewilliamswtn/commit/cc99b9f0c5674b88c261edfad7a4fb47acf3c9b9#diff-db8f629adc6c4c33f29613cfb71a6038R17

Always initialize your variables with `var` in for loops: `for (var i = 0; ...`

**Comment by sscotth** [comment]
https://github.com/nss-day-cohort-15/static-web-js-quiz-ewilliamswtn/commit/cc99b9f0c5674b88c261edfad7a4fb47acf3c9b9#diff-db8f629adc6c4c33f29613cfb71a6038R21

https://github.com/nss-day-cohort-15/static-web-js-quiz-ewilliamswtn/commit/cc99b9f0c5674b88c261edfad7a4fb47acf3c9b9#diff-db8f629adc6c4c33f29613cfb71a6038R34

Consider using a template strings here

**Comment by sscotth** [comment]
https://github.com/nss-day-cohort-15/static-web-js-quiz-ewilliamswtn/commit/cc99b9f0c5674b88c261edfad7a4fb47acf3c9b9#diff-db8f629adc6c4c33f29613cfb71a6038R36

`spaces -= 1` or `spaces--`

**Comment by sscotth** [comment]
There is one feature that your app is missing to meet minimum requirements:

> Once the user enters in a number, and a character, the user can ... then just press the enter key (as long as the cursor is in one of the input fields) ...
> This requires you to add an event listener to the button, as well as an event listener for the enter/return key.

**Comment by gregkorte** [comment]
You are good to merge. :+1:

**Comment by ewilliamswtn** [comment]
Great, thank you!
